//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class members
    {
        public int mem_id { get; set; }
        public int user_id { get; set; }
        public int server_id { get; set; }
    
        public virtual servers servers { get; set; }
        public virtual users users { get; set; }
    }
}
