//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class servers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servers()
        {
            this.members = new HashSet<members>();
            this.msgs = new HashSet<msgs>();
        }
    
        public int server_id { get; set; }
        public string server_name { get; set; }
        public int server_size { get; set; }
        public int server_admin { get; set; }
        public string server_description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<members> members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msgs> msgs { get; set; }
        public virtual users users { get; set; }
    }
}
